FROM mambaorg/micromamba:latest

WORKDIR /

COPY . .

# Install system dependencies first
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Create and own the micromamba directory
RUN mkdir -p /opt/conda/envs/Raspitouille-docker
    # && chown -R micromamba:micromamba /opt/conda

# Switch back to micromamba user
# USER micromamba

RUN micromamba config append channels conda-forge

RUN micromamba create -y -n Raspitouille-docker -f environment.yml

RUN echo "micromamba activate Raspitouille" >> ~/.bashrc

RUN echo "source FlaskExports.sh" >> ~/.bashrc

RUN /bin/bash -c "source ~/.bashrc"

SHELL ["/bin/bash", "-c"]

EXPOSE 5001

CMD ["bash", "-c", "source ~/.bashrc && flask run"]